version: "3"
services:
  mongo:
    image: mongo
    ports:
      - 27018:27017
    restart: always
    volumes:
      - ./data/db:/data/db
  back:
    build: .
    command: npm run serve
    depends_on:
      - mongo
    environment:
      APP_NAME: rpgen
      DEBUG: rpgen:*
      PORT: 8082
      LOG_LEVEL: debug
      MONGO_URI: "mongodb://mongo:27017/rpgen"
    links:
      - mongo
    ports:
      - 8082:8082
    restart: always
    volumes:
      - ./package.json:/app/package.json
      - ./node_modules:/app/node_modules
      - ./data:/app/data
      - ./src:/app/src
      - ./public:/app/public
  mongo-express:
    depends_on:
      - mongo
    image: mongo-express
    links:
      - mongo
    ports:
      - 8091:8081
    restart: always
